#! /bin/sh
[[ -f ~/.Xresources.local ]] && xrdb -merge -I$HOME ~/.Xresources.local
[[ -f ~/.config.custom ]] && . ~/.config.custom
[[ -f ~/.env_vars ]] && . ~/.env_vars

bspc config border_width         0
bspc config top_padding		      40
bspc config window_gap          12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config honor_size_hints	true
bspc config ignore_ewmh_focus   true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Slack desktop=slack
bspc rule -a jetbrains-rubymine desktop=code
bspc rule -a Google-chrome:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb state=floating
bspc monitor $PRIMARY_MONITOR -d terminal chrome chat camera
xsetroot -cursor_name left_ptr
xset s off -dpms #Disable screen power off
picom &
feh --bg-max --randomize ~/.wallpaper/*
dunst &
autolock -time 50 -locker 'i3lock --nofork' &
xss-lock --transfer-sleep-lock -- i3lock --nofork &
export SXHKD_SHELL="sh"

exec sxhkd -r ~/.log/sxhkd.log &
~/.config/polybar/launch.sh
