[tools]
deno = "latest"
direnv = "latest"
go = "latest"
java = "latest"
julia = "latest"
lua = "latest"
node = "latest"
ocaml = "latest"
perl = "latest"
php = "latest"
pnpm = "latest"
python = "system"
yarn = "latest"
