[tools]
bun = "latest"
deno = "latest"
direnv = "latest"
go = "latest"
java = "latest"
julia = "latest"
lua = "latest"
node = "latest"
ocaml = "latest"
opentofu = "latest"
perl = "latest"
php = "latest"
pnpm = "latest"
python = "system"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["pytho", "python"]
